use PMDB

go

set nocount on

declare @company_id unsigned bigint
declare @mobile_no varchar(20)

select @mobile_no = '0910021160'

select @company_id = COMPANY_ID from PM_COMPANY where COMPANY_ABBR = 'AWN'

insert into PM_ADJUST_BOS
(BATCH_ID, TRANSACTION_ID, MOBILE_NO, PAYMENT_TYPE, MAIN_PRODUCT_ID, MAIN_PRODUCT_SEQUENCE_ID
, MAIN_PROMOTION_STATUS, BRAND, CUSTOMER_SEGMENT, SUBSCRIBER_SEGMENT, IS_TEST_NUMBER_BOO
, COMPANY_ID, NON_MOBILE, USER_TYPE, ACCOUNT_ID, SINGLE_BAL_BOO, SPECIFICATION_ID
, OPERATION_DTM, OPERATION_DATE, REQUEST_ACTION, ASSET_TYPE, ADJUST_VALUE, OLD_VALUE, NEW_VALUE
, CURRENT_STATE, PREVIOUS_STATE, NEW_SUSPEND_FLG, OLD_SUSPEND_FLG, NEW_FRAUD_FLG, OLD_FRAUD_FLG
, NEW_SUSPEND_TYPE, OLD_SUSPEND_TYPE, SYS_PREPAID_BAL_LIMIT, NEGATIVE_BAL, CHANNEL, SOURCE_SYSTEM
, REMARKS, TRANSPARENT_DATA_1, TRANSPARENT_DATA_2
, CREATED_BY, CREATED, LAST_UPD_BY, LAST_UPD)
values
(0, '00201606160901000009', @mobile_no, 'Pre-paid', 1, 1
, 'Active', '3G', 'B', 'Standard', 'N'
, @company_id, 'Mobile', 'Pre-paid', '1', 'Y', 8001
, '20160615', '20160615', 'Add Amount',  0, 3.07, '0', '3.07'
, 'Active', 'Active', 'Normal', 'Normal', 'No Fraud', 'No Fraud'
, 'Normal', 'Normal', 0, 0, 1, 'EAI Orders'
, '11111111', 'MPAYRVS', NULL
, 'unit', '20160615', 'unit', '20160615')

go

 
