export BATCH_FILE_PATH=/app/payment/batch/dcb_refund
export INTERFACE_FILE=flexiPriceRefundPaidTransactionService_20140526_1111_DCBcwdc1google_20140526111201.dat
export ADJUST_IN_PATH=/export/home/MNT_NFS/bos1/BSSBroker/input/AdjustBalance
export ADJUST_OUT_PATH=/export/home/MNT_NFS/bos1/BSSBroker/output/AdjustBalance
